-- MySQL Script generated by MySQL Workbench
-- Mon Jul 10 17:06:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema think
-- -----------------------------------------------------
-- thinkphp 5 商城数据库

-- -----------------------------------------------------
-- Schema think
--
-- thinkphp 5 商城数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `think` DEFAULT CHARACTER SET utf8 ;
USE `think` ;

-- -----------------------------------------------------
-- Table `think`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `think`.`admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT COMMENT '后台管理员ID',
  `admin_name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '后台管理员账号',
  `admin_password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '后台管理员密码',
  `admin_user` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '后台账号使用者\n',
  PRIMARY KEY (`admin_id`))
ENGINE = MyISAM
COMMENT = '后台管理员表';


-- -----------------------------------------------------
-- Table `think`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `think`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT COMMENT '商品栏目ID',
  `category_name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '栏目分类名称',
  `catep_id` TINYINT(20) NOT NULL DEFAULT 0 COMMENT '所属栏目字段',
  PRIMARY KEY (`category_id`))
ENGINE = MyISAM
COMMENT = '商品栏目表';


-- -----------------------------------------------------
-- Table `think`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `think`.`goods` (
  `goods_id` INT NOT NULL AUTO_INCREMENT COMMENT '商品ID',
  `goods_name` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '商品名称',
  `goods_price` TINYINT(255) NOT NULL DEFAULT 0 COMMENT '商品价格',
  `goods_src` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '商品缩略图',
  `goods_type` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '商品类型',
  `is_recommend` TINYINT(10) NOT NULL DEFAULT 0 COMMENT '是否为推荐位',
  `is_hot` TINYINT(10) NOT NULL DEFAULT 0 COMMENT '是否为爆款',
  `category_category_id` INT NOT NULL,
  `goods_descride` TEXT NOT NULL COMMENT '商品详情',
  PRIMARY KEY (`goods_id`),
  INDEX `fk_goods_category1_idx` (`category_category_id` ASC))
ENGINE = MyISAM
COMMENT = '商品表';


-- -----------------------------------------------------
-- Table `think`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `think`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户主键ID\n',
  `user_name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '用户账号',
  `user_password` VARCHAR(45) NOT NULL DEFAULT '',
  `user_email` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '用户邮箱地址',
  `user_phone` INT NOT NULL DEFAULT 0 COMMENT '用户联系电话',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = MyISAM
COMMENT = '商城会员用户表';


-- -----------------------------------------------------
-- Table `think`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `think`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_content` TEXT NOT NULL COMMENT '商品评价内容',
  `user_user_id` INT NOT NULL,
  `goods_goods_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`, `user_user_id`),
  INDEX `fk_comment_user1_idx` (`user_user_id` ASC),
  INDEX `fk_comment_goods1_idx` (`goods_goods_id` ASC))
ENGINE = MyISAM
COMMENT = '用户评论表';


-- -----------------------------------------------------
-- Table `think`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `think`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT COMMENT '收货地址ID',
  `address_details` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '收货地址详情',
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `fk_address_user1_idx` (`user_user_id` ASC))
ENGINE = MyISAM
COMMENT = '收货地址表';


-- -----------------------------------------------------
-- Table `think`.`order_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `think`.`order_goods` (
  `order_goods_id` INT NOT NULL AUTO_INCREMENT,
  `order_goods_num` INT NOT NULL DEFAULT 0 COMMENT '购买商品数量',
  `goods_goods_id` INT NOT NULL,
  PRIMARY KEY (`order_goods_id`),
  INDEX `fk_order_goods_goods1_idx` (`goods_goods_id` ASC))
ENGINE = MyISAM
COMMENT = '订单商品表';


-- -----------------------------------------------------
-- Table `think`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `think`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT COMMENT '订单编号',
  `order_time` TIME NULL COMMENT '订单下单时间',
  `user_user_id` INT NOT NULL,
  `order_goods_order_goods_id` INT NOT NULL,
  `is_payment` TINYINT(20) NOT NULL DEFAULT 0 COMMENT '是否支付',
  `is_shipment` TINYINT(20) NOT NULL DEFAULT 0 COMMENT '是否发货',
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user1_idx` (`user_user_id` ASC),
  INDEX `fk_order_order_goods1_idx` (`order_goods_order_goods_id` ASC))
ENGINE = MyISAM
COMMENT = '订单表';


-- -----------------------------------------------------
-- Table `think`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `think`.`Stock` (
  `stock_id` INT NOT NULL AUTO_INCREMENT,
  `Stock_num` INT NOT NULL DEFAULT 0 COMMENT '商品剩余库存',
  `goods_goods_id` INT NOT NULL,
  PRIMARY KEY (`stock_id`),
  INDEX `fk_Stock_goods1_idx` (`goods_goods_id` ASC))
ENGINE = MyISAM
COMMENT = '商品库存表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
